/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.StudentGradeBLL;
import DAO.StudentGradeDAO;
import DTO.StudentGradeDTO;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import GUI.StudentGradeDetails;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author HP
 */
public class StudentGradeMainForm extends javax.swing.JPanel {

    /**
     * Creates new form StudentGradeMainForm
     */
    private StudentGradeBLL studentGradeBLL;
    private StudentGradeDetails studentGradeDetails;
    public StudentGradeMainForm() {
        studentGradeBLL = new StudentGradeBLL();
        initComponents();
        
        loadDataToTable();
        addTableRowClickListener();
    }

private void addTableRowClickListener() {
    jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable2.getSelectedRow();
                if (selectedRow >= 0) {
                    Object enrollmentIdObj = jTable2.getValueAt(selectedRow, 0);
                    if (enrollmentIdObj != null) {
                        String enrollmentId = enrollmentIdObj.toString();
                        // Kiểm tra xem enrollmentId có giá trị hợp lệ không
                        if (!enrollmentId.isEmpty()) {
                            StudentGradeDTO selectedStudentGrade = studentGradeBLL.getStudentGradeByCondition("EnrollmentID = " + enrollmentId);
                            if (selectedStudentGrade != null) {
                                if (studentGradeDetails == null) {
                                    studentGradeDetails = new StudentGradeDetails();
                                }
                                studentGradeDetails.setStudentGrade(selectedStudentGrade);
                                JFrame frame = new JFrame();
                                frame.getContentPane().add(studentGradeDetails);
                                frame.pack();
                                frame.setVisible(true);
                            } else {
                                System.out.println("Không tìm thấy thông tin sinh viên với enrollmentId: " + enrollmentId);
                            }
                        } else {
                            System.out.println("enrollmentId không hợp lệ");
                        }
                    } else {
                        System.out.println("enrollmentId không tồn tại trong hàng được chọn");
                    }
                }
            }
        }
    });
}







    
    private void loadDataToTable() {
        ArrayList<StudentGradeDTO> studentGrades = studentGradeBLL.getAll();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        for (StudentGradeDTO studentGrade : studentGrades) {
            Object[] rowData = {
                studentGrade.getEnrollmentId(),
                studentGrade.getCourse().getCourseId(),
                studentGrade.getCourse().getTitle(),
                studentGrade.getStudent().getPersonId(),
                studentGrade.getStudent().getFirstName(),
                studentGrade.getStudent().getLastName(),
                studentGrade.getGrade()
            };
            model.addRow(rowData);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton_dau = new javax.swing.JButton();
        jButton_prev = new javax.swing.JButton();
        jLabel_trang = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();
        jButton_cuoi = new javax.swing.JButton();
        jLabel_so_trang = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Search by ID");
        jTextField4.setPreferredSize(new java.awt.Dimension(82, 32));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setText("ADD");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButton_dau.setBackground(new java.awt.Color(242, 240, 240));
        jButton_dau.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_dau.setText("<<");
        jPanel4.add(jButton_dau);

        jButton_prev.setBackground(new java.awt.Color(242, 240, 240));
        jButton_prev.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_prev.setText("<");
        jPanel4.add(jButton_prev);

        jLabel_trang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_trang.setText("0");
        jPanel4.add(jLabel_trang);

        jButton_next.setBackground(new java.awt.Color(242, 240, 240));
        jButton_next.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_next.setText(">");
        jPanel4.add(jButton_next);

        jButton_cuoi.setBackground(new java.awt.Color(242, 240, 240));
        jButton_cuoi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton_cuoi.setText(">>");
        jPanel4.add(jButton_cuoi);

        jLabel_so_trang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_so_trang.setText("0/0");
        jPanel4.add(jLabel_so_trang);

        jButton1.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1);

        jScrollPane3.setAutoscrolls(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Enrollment ID", "Course ID", "Title", "Student ID", "First Name", "Last Name", "Grade"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        StudentGradeAdd customPanel = new StudentGradeAdd();  // Thay bằng panel của bạn
        String dialogTitle = "Add New Student Grade";  // Thay bằng tiêu đề mong muốn

        JDialogGUI customDialog;
        customDialog = new JDialogGUI(this, customPanel, dialogTitle);
        customDialog.showDialog();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
        if (jTextField4.getText().equals("Search by ID")) {
                        jTextField4.setText("");
                        jTextField4.setForeground(Color.BLACK);
                    }
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        if (jTextField4.getText().isEmpty()) {
                        jTextField4.setText("Search by ID");
                        jTextField4.setForeground(Color.GRAY);
                    }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      // Gọi phương thức để lấy dữ liệu mới từ nguồn của bạn
    ArrayList<StudentGradeDTO> newData = studentGradeBLL.getAll();
    
    // Cập nhật dữ liệu vào TableModel
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ trong bảng
    
    // Thêm dữ liệu mới vào bảng
    for (StudentGradeDTO studentGrade : newData) {
        model.addRow(new Object[]{
            studentGrade.getEnrollmentId(),
            studentGrade.getCourse().getCourseId(),
            studentGrade.getCourse().getTitle(),
            studentGrade.getStudent().getPersonId(),
            studentGrade.getStudent().getFirstName(),
            studentGrade.getStudent().getLastName(),
            studentGrade.getGrade()
        });
    }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_cuoi;
    private javax.swing.JButton jButton_dau;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_prev;
    private javax.swing.JLabel jLabel_so_trang;
    private javax.swing.JLabel jLabel_trang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
